
server.port=8080

spring.datasource.url=jdbc:mysql://mysqlData1:3306/ems
spring.datasource.username=mouad
spring.datasource.password=00000
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.jpa.defer-datasource-initialization=true
